#!/usr/bin/env python3
"""Verify and optionally repair Esperanto audio generated by RHVoice/Spomenka."""

from __future__ import annotations

import argparse
import concurrent.futures
import csv
import shutil
import subprocess
import tempfile
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from vocab_grouping import _default_audio_key  # noqa: E402
from data_sources import PHRASE_ID_OFFSET  # noqa: E402

PHRASE_CSV = ROOT / "phrases_eo_en_ja_zh_ko_ru_fulfilled_260505.csv"
VOCAB_CSV = ROOT / "2890 Gravaj Esperantaj Vortoj kun Signifoj en la Japana, Ĉina kaj Korea_260505_plej_nova.csv"
PHRASE_AUDIO_DIR = ROOT / "Esperanto例文5000文_収録音声"
VOCAB_AUDIO_DIR = ROOT / "audio"
MOBILE_PHRASE_AUDIO_DIR = ROOT / "mobile_app" / "sentence-audio"
MOBILE_VOCAB_AUDIO_DIR = ROOT / "mobile_app" / "audio"


@dataclass(frozen=True)
class AudioItem:
    kind: str
    item_id: str
    key: str
    text: str
    root_audio: Path
    mobile_audio: Path


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def phrase_audio_key(phrase_id: int, phrase: str) -> str:
    return f"{phrase_id - PHRASE_ID_OFFSET:04d}_{_default_audio_key(phrase)}"


def phrase_items() -> list[AudioItem]:
    items: list[AudioItem] = []
    for row in read_csv(PHRASE_CSV):
        phrase_id = int(str(row["PhraseID"]).strip())
        phrase = str(row["Esperanto"]).strip()
        key = phrase_audio_key(phrase_id, phrase)
        items.append(
            AudioItem(
                kind="phrase",
                item_id=str(phrase_id),
                key=key,
                text=phrase,
                root_audio=PHRASE_AUDIO_DIR / f"{key}.wav",
                mobile_audio=MOBILE_PHRASE_AUDIO_DIR / f"{key}.wav",
            )
        )
    return items


def vocab_items() -> list[AudioItem]:
    rows = read_csv(VOCAB_CSV)
    esperanto_col = "Esperanto" if "Esperanto" in rows[0] else "EO"
    by_key: dict[str, str] = {}
    for row in rows:
        word = str(row[esperanto_col]).strip()
        by_key.setdefault(_default_audio_key(word), word)

    return [
        AudioItem(
            kind="vocab",
            item_id=key,
            key=key,
            text=word,
            root_audio=VOCAB_AUDIO_DIR / f"{key}.wav",
            mobile_audio=MOBILE_VOCAB_AUDIO_DIR / f"{key}.wav",
        )
        for key, word in sorted(by_key.items())
    ]


def synthesize_spomenka(item: AudioItem, out_path: Path, *, voice: str, sample_rate: int) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [
            "RHVoice-test",
            "-p",
            voice,
            "-R",
            str(sample_rate),
            "-o",
            str(out_path),
        ],
        input=f"{item.text}\n",
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip()
        raise RuntimeError(detail or f"RHVoice-test exited with {result.returncode}")


def check_item(args: tuple[AudioItem, Path, str, int]) -> dict[str, str]:
    item, tmp_dir, voice, sample_rate = args
    generated = tmp_dir / item.kind / f"{item.key}.wav"
    try:
        if not item.root_audio.exists():
            return result_row(item, "missing_root", "", "")
        if not item.mobile_audio.exists():
            return result_row(item, "missing_mobile", str(item.root_audio.stat().st_size), "")
        synthesize_spomenka(item, generated, voice=voice, sample_rate=sample_rate)
        generated_bytes = generated.read_bytes()
        root_bytes = item.root_audio.read_bytes()
        mobile_bytes = item.mobile_audio.read_bytes()
        if root_bytes != mobile_bytes:
            return result_row(item, "root_mobile_different", str(len(root_bytes)), str(len(mobile_bytes)))
        if root_bytes != generated_bytes:
            return result_row(item, "not_spomenka_exact", str(len(root_bytes)), str(len(generated_bytes)))
        return result_row(item, "ok", str(len(root_bytes)), str(len(generated_bytes)))
    except Exception as exc:  # pragma: no cover - command-line diagnostic
        return result_row(item, f"error: {exc}", "", "")


def result_row(item: AudioItem, status: str, existing_size: str, generated_size: str) -> dict[str, str]:
    return {
        "kind": item.kind,
        "id": item.item_id,
        "key": item.key,
        "text": item.text,
        "status": status,
        "existing_size": existing_size,
        "generated_size": generated_size,
    }


def write_report(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["kind", "id", "key", "text", "status", "existing_size", "generated_size"],
        )
        writer.writeheader()
        writer.writerows(rows)


def repair_rows(
    rows: list[dict[str, str]],
    items_by_key: dict[tuple[str, str], AudioItem],
    *,
    voice: str,
    sample_rate: int,
) -> int:
    repairable = [row for row in rows if row["status"] == "not_spomenka_exact"]
    repaired = 0
    with tempfile.TemporaryDirectory(prefix="spomenka-repair-") as tmp_name:
        tmp_dir = Path(tmp_name)
        for row in repairable:
            item = items_by_key[(row["kind"], row["key"])]
            generated = tmp_dir / item.kind / f"{item.key}.wav"
            synthesize_spomenka(item, generated, voice=voice, sample_rate=sample_rate)
            shutil.copyfile(generated, item.root_audio)
            shutil.copyfile(generated, item.mobile_audio)
            repaired += 1
    return repaired


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kind", choices=["phrases", "vocab", "all"], default="all")
    parser.add_argument("--voice", default="spomenka")
    parser.add_argument("--sample-rate", type=int, default=24000)
    parser.add_argument("--workers", type=int, default=6)
    parser.add_argument("--repair", action="store_true", help="Replace non-Spomenka-exact root and mobile WAV files.")
    parser.add_argument("--report", default="", help="Optional CSV report path.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not shutil.which("RHVoice-test"):
        raise SystemExit("RHVoice-test was not found in PATH.")

    items: list[AudioItem] = []
    if args.kind in {"phrases", "all"}:
        items.extend(phrase_items())
    if args.kind in {"vocab", "all"}:
        items.extend(vocab_items())

    with tempfile.TemporaryDirectory(prefix="spomenka-verify-") as tmp_name:
        tmp_dir = Path(tmp_name)
        tasks = [(item, tmp_dir, args.voice, args.sample_rate) for item in items]
        with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, args.workers)) as executor:
            rows = list(executor.map(check_item, tasks, chunksize=8))

    problems = [row for row in rows if row["status"] != "ok"]
    counts: dict[str, int] = {}
    for row in rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1

    if args.report:
        write_report(ROOT / args.report, rows)

    repaired = 0
    if args.repair:
        items_by_key = {(item.kind, item.key): item for item in items}
        repaired = repair_rows(rows, items_by_key, voice=args.voice, sample_rate=args.sample_rate)

    print(f"checked={len(rows)}")
    for status, count in sorted(counts.items()):
        print(f"{status}={count}")
    if repaired:
        print(f"repaired={repaired}")
    for row in problems[:30]:
        print(f"{row['kind']}\t{row['id']}\t{row['key']}\t{row['status']}\t{row['text']}")
    return 1 if problems and not args.repair else 0


if __name__ == "__main__":
    raise SystemExit(main())
